//
//Copyright 2023 The Dapr Authors
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: dapr/proto/actors/v1/actors.proto

package actors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServiceInfoRequest) Reset() {
	*x = ServiceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoRequest) ProtoMessage() {}

func (x *ServiceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoRequest.ProtoReflect.Descriptor instead.
func (*ServiceInfoRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{0}
}

type ServiceInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Version of the actors service.
	// This is indicated as an integer.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ServiceInfoResponse) Reset() {
	*x = ServiceInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoResponse) ProtoMessage() {}

func (x *ServiceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoResponse.ProtoReflect.Descriptor instead.
func (*ServiceInfoResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceInfoResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ConnectHostClientStream is sent by the Dapr sidecar to the Actors service.
// The first message in the stream must contain the required fields; subsequent messages could be empty, but including fields is allowed to provide updates.
type ConnectHostClientStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Message to include.
	// This is optional, and no message indicates a simple ping (for health checks).
	// However, the first message sent must include a RegisterActorHost.
	//
	// Types that are assignable to Message:
	//
	//	*ConnectHostClientStream_RegisterActorHost
	Message isConnectHostClientStream_Message `protobuf_oneof:"message"`
}

func (x *ConnectHostClientStream) Reset() {
	*x = ConnectHostClientStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectHostClientStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectHostClientStream) ProtoMessage() {}

func (x *ConnectHostClientStream) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectHostClientStream.ProtoReflect.Descriptor instead.
func (*ConnectHostClientStream) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{2}
}

func (m *ConnectHostClientStream) GetMessage() isConnectHostClientStream_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ConnectHostClientStream) GetRegisterActorHost() *RegisterActorHost {
	if x, ok := x.GetMessage().(*ConnectHostClientStream_RegisterActorHost); ok {
		return x.RegisterActorHost
	}
	return nil
}

type isConnectHostClientStream_Message interface {
	isConnectHostClientStream_Message()
}

type ConnectHostClientStream_RegisterActorHost struct {
	// The first message sent in ConnectHost by the sidecar must contain RegisterActorHost.
	// The sidecar can re-send this message at any time to update its registration.
	RegisterActorHost *RegisterActorHost `protobuf:"bytes,1,opt,name=register_actor_host,json=registerActorHost,proto3,oneof"`
}

func (*ConnectHostClientStream_RegisterActorHost) isConnectHostClientStream_Message() {}

// RegisterActorHost is sent by the Dapr sidecar to the Actors service.
// It includes information on the current sidecar's actor hosting capabilities.
type RegisterActorHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Address, including port
	// Required on the first message; cannot be updated
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Dapr App ID
	// Format is 'namespace/app-id' or just 'app-id'
	// Required on the first message; cannot be updated
	AppId string `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Version of the Actor APIs supported by the Dapr runtime
	// Required on the first message; cannot be updated
	ApiLevel uint32 `protobuf:"varint,3,opt,name=api_level,json=apiLevel,proto3" json:"api_level,omitempty"`
	// List of supported actor types.
	ActorTypes []*ActorHostType `protobuf:"bytes,4,rep,name=actor_types,json=actorTypes,proto3" json:"actor_types,omitempty"`
}

func (x *RegisterActorHost) Reset() {
	*x = RegisterActorHost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterActorHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterActorHost) ProtoMessage() {}

func (x *RegisterActorHost) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterActorHost.ProtoReflect.Descriptor instead.
func (*RegisterActorHost) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterActorHost) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterActorHost) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RegisterActorHost) GetApiLevel() uint32 {
	if x != nil {
		return x.ApiLevel
	}
	return 0
}

func (x *RegisterActorHost) GetActorTypes() []*ActorHostType {
	if x != nil {
		return x.ActorTypes
	}
	return nil
}

// ActorHostType references a supported actor type.
type ActorHostType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Actor type name
	ActorType string `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	// Actor idle timeout, in seconds
	IdleTimeout uint32 `protobuf:"varint,2,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
}

func (x *ActorHostType) Reset() {
	*x = ActorHostType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorHostType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorHostType) ProtoMessage() {}

func (x *ActorHostType) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorHostType.ProtoReflect.Descriptor instead.
func (*ActorHostType) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{4}
}

func (x *ActorHostType) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *ActorHostType) GetIdleTimeout() uint32 {
	if x != nil {
		return x.IdleTimeout
	}
	return 0
}

// ConnectHostServerStream is sent by the Actors service to the Dapr sidecar.
// The message could be empty, in which case it acts as a response to a "ping" message.
type ConnectHostServerStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Message to include.
	// This is optional, and no message indicates a simple ping.
	//
	// Types that are assignable to Message:
	//
	//	*ConnectHostServerStream_ActorHostConfiguration
	//	*ConnectHostServerStream_ExecuteReminder
	//	*ConnectHostServerStream_DeactivateActor
	Message isConnectHostServerStream_Message `protobuf_oneof:"message"`
}

func (x *ConnectHostServerStream) Reset() {
	*x = ConnectHostServerStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectHostServerStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectHostServerStream) ProtoMessage() {}

func (x *ConnectHostServerStream) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectHostServerStream.ProtoReflect.Descriptor instead.
func (*ConnectHostServerStream) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{5}
}

func (m *ConnectHostServerStream) GetMessage() isConnectHostServerStream_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ConnectHostServerStream) GetActorHostConfiguration() *ActorHostConfiguration {
	if x, ok := x.GetMessage().(*ConnectHostServerStream_ActorHostConfiguration); ok {
		return x.ActorHostConfiguration
	}
	return nil
}

func (x *ConnectHostServerStream) GetExecuteReminder() *ExecuteReminder {
	if x, ok := x.GetMessage().(*ConnectHostServerStream_ExecuteReminder); ok {
		return x.ExecuteReminder
	}
	return nil
}

func (x *ConnectHostServerStream) GetDeactivateActor() *DeactivateActor {
	if x, ok := x.GetMessage().(*ConnectHostServerStream_DeactivateActor); ok {
		return x.DeactivateActor
	}
	return nil
}

type isConnectHostServerStream_Message interface {
	isConnectHostServerStream_Message()
}

type ConnectHostServerStream_ActorHostConfiguration struct {
	// Send certain configuration options for the actor subsystem to the actor host.
	// This is normally sent in response to the first message from the actor host, but can be sent as update at any time.
	ActorHostConfiguration *ActorHostConfiguration `protobuf:"bytes,1,opt,name=actor_host_configuration,json=actorHostConfiguration,proto3,oneof"`
}

type ConnectHostServerStream_ExecuteReminder struct {
	// Start the execution of a reminder.
	ExecuteReminder *ExecuteReminder `protobuf:"bytes,2,opt,name=execute_reminder,json=executeReminder,proto3,oneof"`
}

type ConnectHostServerStream_DeactivateActor struct {
	// Deactivate an actor
	DeactivateActor *DeactivateActor `protobuf:"bytes,3,opt,name=deactivate_actor,json=deactivateActor,proto3,oneof"`
}

func (*ConnectHostServerStream_ActorHostConfiguration) isConnectHostServerStream_Message() {}

func (*ConnectHostServerStream_ExecuteReminder) isConnectHostServerStream_Message() {}

func (*ConnectHostServerStream_DeactivateActor) isConnectHostServerStream_Message() {}

// ActorHostConfiguration is one of the messages that cna be sent by ConnectHostServerStream.
// It contains certain configuration options for the actor subsystem.
// This is normally sent in response to the first message from the actor host, but can be sent as update at any time.
type ActorHostConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Maximum interval for the actor host to send pings to the actors service.
	HealthCheckInterval uint32 `protobuf:"varint,1,opt,name=health_check_interval,json=healthCheckInterval,proto3" json:"health_check_interval,omitempty"`
}

func (x *ActorHostConfiguration) Reset() {
	*x = ActorHostConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorHostConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorHostConfiguration) ProtoMessage() {}

func (x *ActorHostConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorHostConfiguration.ProtoReflect.Descriptor instead.
func (*ActorHostConfiguration) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{6}
}

func (x *ActorHostConfiguration) GetHealthCheckInterval() uint32 {
	if x != nil {
		return x.HealthCheckInterval
	}
	return 0
}

// ExecuteReminder is one of the messages that cna be sent by ConnectHostServerStream.
// It is sent to tell the sidecar to execute a reminder.
// The sidecar is expected to respond right away, and then acknowledge that the reminder
// has been completely executed with ReminderCompleted.
type ExecuteReminder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Reference for the execution, which must be sent back in the ReminderComplete request.
	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Reminder that is to be executed
	Reminder *Reminder `protobuf:"bytes,2,opt,name=reminder,proto3" json:"reminder,omitempty"`
}

func (x *ExecuteReminder) Reset() {
	*x = ExecuteReminder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteReminder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteReminder) ProtoMessage() {}

func (x *ExecuteReminder) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteReminder.ProtoReflect.Descriptor instead.
func (*ExecuteReminder) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteReminder) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ExecuteReminder) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

type ActorRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorType string `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId   string `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
}

func (x *ActorRef) Reset() {
	*x = ActorRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRef) ProtoMessage() {}

func (x *ActorRef) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRef.ProtoReflect.Descriptor instead.
func (*ActorRef) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{8}
}

func (x *ActorRef) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *ActorRef) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

// ExecuteReminder is one of the messages that cna be sent by ConnectHostServerStream.
// It is sent to tell the sidecar to deactivate an actor.
type DeactivateActor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor *ActorRef `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *DeactivateActor) Reset() {
	*x = DeactivateActor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeactivateActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateActor) ProtoMessage() {}

func (x *DeactivateActor) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateActor.ProtoReflect.Descriptor instead.
func (*DeactivateActor) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{9}
}

func (x *DeactivateActor) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ReminderCompletedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Reference for the execution, which was sent in the ExecuteReminder message.
	Ref string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *ReminderCompletedRequest) Reset() {
	*x = ReminderCompletedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReminderCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderCompletedRequest) ProtoMessage() {}

func (x *ReminderCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderCompletedRequest.ProtoReflect.Descriptor instead.
func (*ReminderCompletedRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{10}
}

func (x *ReminderCompletedRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type ReminderCompletedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReminderCompletedResponse) Reset() {
	*x = ReminderCompletedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReminderCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderCompletedResponse) ProtoMessage() {}

func (x *ReminderCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderCompletedResponse.ProtoReflect.Descriptor instead.
func (*ReminderCompletedResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{11}
}

type LookupActorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Actor reference.
	Actor *ActorRef `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *LookupActorRequest) Reset() {
	*x = LookupActorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupActorRequest) ProtoMessage() {}

func (x *LookupActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupActorRequest.ProtoReflect.Descriptor instead.
func (*LookupActorRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{12}
}

func (x *LookupActorRequest) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

type LookupActorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Dapr App ID of the host
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Host address (including port)
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Actor idle timeout, in seconds
	// (Note that this is the absolute idle timeout, and not the remaining lifetime of the actor)
	IdleTimeout uint32 `protobuf:"varint,3,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
}

func (x *LookupActorResponse) Reset() {
	*x = LookupActorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupActorResponse) ProtoMessage() {}

func (x *LookupActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupActorResponse.ProtoReflect.Descriptor instead.
func (*LookupActorResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{13}
}

func (x *LookupActorResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *LookupActorResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LookupActorResponse) GetIdleTimeout() uint32 {
	if x != nil {
		return x.IdleTimeout
	}
	return 0
}

type ReportActorDeactivationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor *ActorRef `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *ReportActorDeactivationRequest) Reset() {
	*x = ReportActorDeactivationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportActorDeactivationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportActorDeactivationRequest) ProtoMessage() {}

func (x *ReportActorDeactivationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportActorDeactivationRequest.ProtoReflect.Descriptor instead.
func (*ReportActorDeactivationRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{14}
}

func (x *ReportActorDeactivationRequest) GetActor() *ActorRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ReportActorDeactivationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportActorDeactivationResponse) Reset() {
	*x = ReportActorDeactivationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportActorDeactivationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportActorDeactivationResponse) ProtoMessage() {}

func (x *ReportActorDeactivationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportActorDeactivationResponse.ProtoReflect.Descriptor instead.
func (*ReportActorDeactivationResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{15}
}

type ReminderRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorType string `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId   string `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Name of the reminder
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ReminderRef) Reset() {
	*x = ReminderRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReminderRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderRef) ProtoMessage() {}

func (x *ReminderRef) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderRef.ProtoReflect.Descriptor instead.
func (*ReminderRef) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{16}
}

func (x *ReminderRef) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *ReminderRef) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ReminderRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Reminder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorType string `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId   string `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Name of the reminder
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ExecutionTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	// Can be empty; will be parsed in any format supported by Dapr actors
	Period string `protobuf:"bytes,5,opt,name=period,proto3" json:"period,omitempty"`
	// Can be empty
	Ttl *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Can be empty
	Data []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Reminder) Reset() {
	*x = Reminder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reminder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reminder) ProtoMessage() {}

func (x *Reminder) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reminder.ProtoReflect.Descriptor instead.
func (*Reminder) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{17}
}

func (x *Reminder) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *Reminder) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Reminder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Reminder) GetExecutionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutionTime
	}
	return nil
}

func (x *Reminder) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Reminder) GetTtl() *timestamppb.Timestamp {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Reminder) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateReminderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reminder *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
}

func (x *CreateReminderRequest) Reset() {
	*x = CreateReminderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReminderRequest) ProtoMessage() {}

func (x *CreateReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReminderRequest.ProtoReflect.Descriptor instead.
func (*CreateReminderRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{18}
}

func (x *CreateReminderRequest) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

type CreateReminderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateReminderResponse) Reset() {
	*x = CreateReminderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReminderResponse) ProtoMessage() {}

func (x *CreateReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReminderResponse.ProtoReflect.Descriptor instead.
func (*CreateReminderResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{19}
}

type GetReminderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref *ReminderRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *GetReminderRequest) Reset() {
	*x = GetReminderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderRequest) ProtoMessage() {}

func (x *GetReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderRequest.ProtoReflect.Descriptor instead.
func (*GetReminderRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{20}
}

func (x *GetReminderRequest) GetRef() *ReminderRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetReminderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reminder *Reminder `protobuf:"bytes,1,opt,name=reminder,proto3" json:"reminder,omitempty"`
}

func (x *GetReminderResponse) Reset() {
	*x = GetReminderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderResponse) ProtoMessage() {}

func (x *GetReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderResponse.ProtoReflect.Descriptor instead.
func (*GetReminderResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{21}
}

func (x *GetReminderResponse) GetReminder() *Reminder {
	if x != nil {
		return x.Reminder
	}
	return nil
}

type DeleteReminderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref *ReminderRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *DeleteReminderRequest) Reset() {
	*x = DeleteReminderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReminderRequest) ProtoMessage() {}

func (x *DeleteReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReminderRequest.ProtoReflect.Descriptor instead.
func (*DeleteReminderRequest) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteReminderRequest) GetRef() *ReminderRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type DeleteReminderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReminderResponse) Reset() {
	*x = DeleteReminderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReminderResponse) ProtoMessage() {}

func (x *DeleteReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapr_proto_actors_v1_actors_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReminderResponse.ProtoReflect.Descriptor instead.
func (*DeleteReminderResponse) Descriptor() ([]byte, []int) {
	return file_dapr_proto_actors_v1_actors_proto_rawDescGZIP(), []int{23}
}

var File_dapr_proto_actors_v1_actors_proto protoreflect.FileDescriptor

var file_dapr_proto_actors_v1_actors_proto_rawDesc = []byte{
	0x0a, 0x21, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x2f, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x7f, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x59, 0x0a, 0x13,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x61, 0x70, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x6f,
	0x73, 0x74, 0x48, 0x00, 0x52, 0x11, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41,
	0x63, 0x74, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x70, 0x69,
	0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x70,
	0x69, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x44, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x61,
	0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x51, 0x0a, 0x0d,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x69, 0x64, 0x6c, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x69, 0x64, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22,
	0xb6, 0x02, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x68, 0x0a, 0x18, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x16, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x52, 0x0a, 0x10, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x5f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x52, 0x0a, 0x10, 0x64, 0x65, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0f, 0x64, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x42, 0x09, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x48, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x15, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x13, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x5f, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x3a, 0x0a, 0x08, 0x72,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x08, 0x72,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x66, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x47, 0x0a,
	0x0f, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x34, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x52,
	0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x72, 0x65, 0x66, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x4a, 0x0a, 0x12, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x69, 0x0a,
	0x13, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x64, 0x6c, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x69, 0x64, 0x6c,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x56, 0x0a, 0x1e, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x61, 0x70, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x66, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x22, 0x21, 0x0a, 0x1f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x44,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x5b, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x66, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0xf5, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0d, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x2c, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x03, 0x74, 0x74, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x53, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3a, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x18, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x49, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a,
	0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x61, 0x70,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x66, 0x52, 0x03, 0x72,
	0x65, 0x66, 0x22, 0x51, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x72, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x61,
	0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x08, 0x72, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33,
	0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x61,
	0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x66, 0x52, 0x03,
	0x72, 0x65, 0x66, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x8e, 0x07,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x64, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x29, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x71,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x2d, 0x2e,
	0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x2d, 0x2e, 0x64,
	0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x76, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x2e, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x0b, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x28, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x88, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x44,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x2e, 0x64, 0x61,
	0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x35, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41,
	0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x2b, 0x2e, 0x64,
	0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x64, 0x61, 0x70, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x28, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x6d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x2b, 0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c,
	0x2e, 0x64, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x70,
	0x72, 0x2f, 0x64, 0x61, 0x70, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dapr_proto_actors_v1_actors_proto_rawDescOnce sync.Once
	file_dapr_proto_actors_v1_actors_proto_rawDescData = file_dapr_proto_actors_v1_actors_proto_rawDesc
)

func file_dapr_proto_actors_v1_actors_proto_rawDescGZIP() []byte {
	file_dapr_proto_actors_v1_actors_proto_rawDescOnce.Do(func() {
		file_dapr_proto_actors_v1_actors_proto_rawDescData = protoimpl.X.CompressGZIP(file_dapr_proto_actors_v1_actors_proto_rawDescData)
	})
	return file_dapr_proto_actors_v1_actors_proto_rawDescData
}

var file_dapr_proto_actors_v1_actors_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_dapr_proto_actors_v1_actors_proto_goTypes = []interface{}{
	(*ServiceInfoRequest)(nil),              // 0: dapr.proto.actors.v1.ServiceInfoRequest
	(*ServiceInfoResponse)(nil),             // 1: dapr.proto.actors.v1.ServiceInfoResponse
	(*ConnectHostClientStream)(nil),         // 2: dapr.proto.actors.v1.ConnectHostClientStream
	(*RegisterActorHost)(nil),               // 3: dapr.proto.actors.v1.RegisterActorHost
	(*ActorHostType)(nil),                   // 4: dapr.proto.actors.v1.ActorHostType
	(*ConnectHostServerStream)(nil),         // 5: dapr.proto.actors.v1.ConnectHostServerStream
	(*ActorHostConfiguration)(nil),          // 6: dapr.proto.actors.v1.ActorHostConfiguration
	(*ExecuteReminder)(nil),                 // 7: dapr.proto.actors.v1.ExecuteReminder
	(*ActorRef)(nil),                        // 8: dapr.proto.actors.v1.ActorRef
	(*DeactivateActor)(nil),                 // 9: dapr.proto.actors.v1.DeactivateActor
	(*ReminderCompletedRequest)(nil),        // 10: dapr.proto.actors.v1.ReminderCompletedRequest
	(*ReminderCompletedResponse)(nil),       // 11: dapr.proto.actors.v1.ReminderCompletedResponse
	(*LookupActorRequest)(nil),              // 12: dapr.proto.actors.v1.LookupActorRequest
	(*LookupActorResponse)(nil),             // 13: dapr.proto.actors.v1.LookupActorResponse
	(*ReportActorDeactivationRequest)(nil),  // 14: dapr.proto.actors.v1.ReportActorDeactivationRequest
	(*ReportActorDeactivationResponse)(nil), // 15: dapr.proto.actors.v1.ReportActorDeactivationResponse
	(*ReminderRef)(nil),                     // 16: dapr.proto.actors.v1.ReminderRef
	(*Reminder)(nil),                        // 17: dapr.proto.actors.v1.Reminder
	(*CreateReminderRequest)(nil),           // 18: dapr.proto.actors.v1.CreateReminderRequest
	(*CreateReminderResponse)(nil),          // 19: dapr.proto.actors.v1.CreateReminderResponse
	(*GetReminderRequest)(nil),              // 20: dapr.proto.actors.v1.GetReminderRequest
	(*GetReminderResponse)(nil),             // 21: dapr.proto.actors.v1.GetReminderResponse
	(*DeleteReminderRequest)(nil),           // 22: dapr.proto.actors.v1.DeleteReminderRequest
	(*DeleteReminderResponse)(nil),          // 23: dapr.proto.actors.v1.DeleteReminderResponse
	(*timestamppb.Timestamp)(nil),           // 24: google.protobuf.Timestamp
}
var file_dapr_proto_actors_v1_actors_proto_depIdxs = []int32{
	3,  // 0: dapr.proto.actors.v1.ConnectHostClientStream.register_actor_host:type_name -> dapr.proto.actors.v1.RegisterActorHost
	4,  // 1: dapr.proto.actors.v1.RegisterActorHost.actor_types:type_name -> dapr.proto.actors.v1.ActorHostType
	6,  // 2: dapr.proto.actors.v1.ConnectHostServerStream.actor_host_configuration:type_name -> dapr.proto.actors.v1.ActorHostConfiguration
	7,  // 3: dapr.proto.actors.v1.ConnectHostServerStream.execute_reminder:type_name -> dapr.proto.actors.v1.ExecuteReminder
	9,  // 4: dapr.proto.actors.v1.ConnectHostServerStream.deactivate_actor:type_name -> dapr.proto.actors.v1.DeactivateActor
	17, // 5: dapr.proto.actors.v1.ExecuteReminder.reminder:type_name -> dapr.proto.actors.v1.Reminder
	8,  // 6: dapr.proto.actors.v1.DeactivateActor.actor:type_name -> dapr.proto.actors.v1.ActorRef
	8,  // 7: dapr.proto.actors.v1.LookupActorRequest.actor:type_name -> dapr.proto.actors.v1.ActorRef
	8,  // 8: dapr.proto.actors.v1.ReportActorDeactivationRequest.actor:type_name -> dapr.proto.actors.v1.ActorRef
	24, // 9: dapr.proto.actors.v1.Reminder.execution_time:type_name -> google.protobuf.Timestamp
	24, // 10: dapr.proto.actors.v1.Reminder.ttl:type_name -> google.protobuf.Timestamp
	17, // 11: dapr.proto.actors.v1.CreateReminderRequest.reminder:type_name -> dapr.proto.actors.v1.Reminder
	16, // 12: dapr.proto.actors.v1.GetReminderRequest.ref:type_name -> dapr.proto.actors.v1.ReminderRef
	17, // 13: dapr.proto.actors.v1.GetReminderResponse.reminder:type_name -> dapr.proto.actors.v1.Reminder
	16, // 14: dapr.proto.actors.v1.DeleteReminderRequest.ref:type_name -> dapr.proto.actors.v1.ReminderRef
	0,  // 15: dapr.proto.actors.v1.Actors.ServiceInfo:input_type -> dapr.proto.actors.v1.ServiceInfoRequest
	2,  // 16: dapr.proto.actors.v1.Actors.ConnectHost:input_type -> dapr.proto.actors.v1.ConnectHostClientStream
	10, // 17: dapr.proto.actors.v1.Actors.ReminderCompleted:input_type -> dapr.proto.actors.v1.ReminderCompletedRequest
	12, // 18: dapr.proto.actors.v1.Actors.LookupActor:input_type -> dapr.proto.actors.v1.LookupActorRequest
	14, // 19: dapr.proto.actors.v1.Actors.ReportActorDeactivation:input_type -> dapr.proto.actors.v1.ReportActorDeactivationRequest
	18, // 20: dapr.proto.actors.v1.Actors.CreateReminder:input_type -> dapr.proto.actors.v1.CreateReminderRequest
	20, // 21: dapr.proto.actors.v1.Actors.GetReminder:input_type -> dapr.proto.actors.v1.GetReminderRequest
	22, // 22: dapr.proto.actors.v1.Actors.DeleteReminder:input_type -> dapr.proto.actors.v1.DeleteReminderRequest
	1,  // 23: dapr.proto.actors.v1.Actors.ServiceInfo:output_type -> dapr.proto.actors.v1.ServiceInfoResponse
	5,  // 24: dapr.proto.actors.v1.Actors.ConnectHost:output_type -> dapr.proto.actors.v1.ConnectHostServerStream
	11, // 25: dapr.proto.actors.v1.Actors.ReminderCompleted:output_type -> dapr.proto.actors.v1.ReminderCompletedResponse
	13, // 26: dapr.proto.actors.v1.Actors.LookupActor:output_type -> dapr.proto.actors.v1.LookupActorResponse
	15, // 27: dapr.proto.actors.v1.Actors.ReportActorDeactivation:output_type -> dapr.proto.actors.v1.ReportActorDeactivationResponse
	19, // 28: dapr.proto.actors.v1.Actors.CreateReminder:output_type -> dapr.proto.actors.v1.CreateReminderResponse
	21, // 29: dapr.proto.actors.v1.Actors.GetReminder:output_type -> dapr.proto.actors.v1.GetReminderResponse
	23, // 30: dapr.proto.actors.v1.Actors.DeleteReminder:output_type -> dapr.proto.actors.v1.DeleteReminderResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_dapr_proto_actors_v1_actors_proto_init() }
func file_dapr_proto_actors_v1_actors_proto_init() {
	if File_dapr_proto_actors_v1_actors_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dapr_proto_actors_v1_actors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectHostClientStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterActorHost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorHostType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectHostServerStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorHostConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteReminder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeactivateActor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReminderCompletedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReminderCompletedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupActorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupActorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportActorDeactivationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportActorDeactivationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReminderRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reminder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReminderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReminderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReminderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReminderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReminderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dapr_proto_actors_v1_actors_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReminderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dapr_proto_actors_v1_actors_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ConnectHostClientStream_RegisterActorHost)(nil),
	}
	file_dapr_proto_actors_v1_actors_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ConnectHostServerStream_ActorHostConfiguration)(nil),
		(*ConnectHostServerStream_ExecuteReminder)(nil),
		(*ConnectHostServerStream_DeactivateActor)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dapr_proto_actors_v1_actors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dapr_proto_actors_v1_actors_proto_goTypes,
		DependencyIndexes: file_dapr_proto_actors_v1_actors_proto_depIdxs,
		MessageInfos:      file_dapr_proto_actors_v1_actors_proto_msgTypes,
	}.Build()
	File_dapr_proto_actors_v1_actors_proto = out.File
	file_dapr_proto_actors_v1_actors_proto_rawDesc = nil
	file_dapr_proto_actors_v1_actors_proto_goTypes = nil
	file_dapr_proto_actors_v1_actors_proto_depIdxs = nil
}
